apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
    name: example-pool
    namespace: metallb-system
spec:
    addresses:
    - 172.18.5.10-172.18.5.20
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
    name: example-l2advertisement
    namespace: metallb-system
spec:
    ipAddressPools:
    - example-pool