kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  # stream-snippets: |
  #   server {
  #     listen 26257;
  #     proxy_pass cockroachdb-public.default.svc.cluster.local:26257;
  #   }
